# -*- coding: utf-8 -*-
"""generar_melspectrograms.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/18pyTeQWpATUx9E3lggaWCg6Pb6_64gob
"""

import os
import glob
import shutil
from itertools import islice
from pathlib import Path
from IPython.display import Audio
import librosa
import librosa.display
import matplotlib.pyplot as plt
import numpy as np
import pandas as pd
from scipy.fftpack import fft
from scipy.signal import get_window
import io
import matplotlib.pyplot as plt
import librosa.display
from skimage import io
from pathlib import Path
from IPython.display import Audio
import os
import shutil, os
from pathlib import Path
import h5py
from random import shuffle as mezclar #Con esta libreria se mezclan los elementos de una lista de objetos
import glob # libreria global
import tables as tabla
import cv2

ruta='/content/drive/MyDrive/database final/aleman/*.mp3' #ruta donde se encuentran los audios
audios=glob.glob(ruta)

def log_mel_spec_tfm(fname, dst_path): #convierte audios en png con duración de 4 segundos
    x, sample_rate = librosa.load(fname, sr=None)
    
    
    four_seconds = sample_rate * 4 #Hace que los audios tengan duracion de 4 segundos
    x = x[:four_seconds]  
    
    n_fft = 1024 # frame length 
    hop_length = 256
    n_mels = 40
    fmin = 20
    fmax = sample_rate / 2 
      
  
    
    mel_spec_power = librosa.feature.melspectrogram(x, sr=sample_rate, n_fft=n_fft, 
                                                    hop_length=hop_length, 
                                                    n_mels=n_mels, power=2.0, 
                                                    fmin=fmin, fmax=fmax)
    mel_spec_db = librosa.power_to_db(mel_spec_power, ref=np.max)
    dst_fname = (dst_path / (fname[:-4] + '.png'))
    plt.imsave(dst_fname, mel_spec_db)

images=[]
for i in range(len(audios)):
  print('número de png:',i)
  if 'de' in audios[i]:
    name = audios[i] # nombre del audio
    filename =  name               #AUDIO + '/' + name
  #Cnvierte todos los melspectrograms del set test a png
    log_mel_spec_tfm(filename, Path('.'))
    img = plt.imread(filename[:-4] + '.png')
    plt.imshow(img, origin='lower');
    images.append(img)